### ISSUE TITLE
React-Table export issue

### ISSUE THREAD

**Issue by ShaneDonaghy** [PacktPublishing/Hands-On-Full-Stack-Development-with-Spring-Boot-2.0-and-React-Second-Edition#1]
p177 in book - integrating react-table to our app. 
In order to code along with the example, be sure and stipulate version 6 is used when installing i.e.
`npm install react-table-6`

The latest version (7 at time of writing) does not have a default export.

**Comment by juhahinkula** [comment]
Thanks for the issue. The version 7 is now major version of react-table component and the functionality is totally different. Therefore the install command is

`npm install react-table-v6`

and import statement is

`import ReactTable from 'react-table-v6'`

**Comment by gaurav-packt** [comment]
Closing the issue as per the feedback shared by the author
